FROM python:3.12-slim

WORKDIR /app

# Copiar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# Copiar el código de aplicación
COPY src ./src
COPY scripts ./scripts

# Exponer puerto y comando
EXPOSE 8000
CMD ["uvicorn", "src.theaia.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
