# ==============================================
# THEA IA 3.0 — DOCKER COMPOSE ENTERPRISE
# ==============================================

version: "3.9"

services:
  api:
    container_name: theaia-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - THEA_ENV=production
      - DATABASE_URL=postgresql+asyncpg://thea_user:thea_password@db:5432/theaia_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    networks:
      - thea-net

  docs:
    container_name: theaia-docs
    build:
      context: .
      dockerfile: Dockerfile
      target: docs
    ports:
      - "8001:8001"
    restart: always
    networks:
      - thea-net

  db:
    image: postgres:16-alpine
    container_name: theaia-db
    environment:
      POSTGRES_USER: thea_user
      POSTGRES_PASSWORD: thea_password
      POSTGRES_DB: theaia_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always
    networks:
      - thea-net

  redis:
    image: redis:7.2-alpine
    container_name: theaia-redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: always
    networks:
      - thea-net

networks:
  thea-net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
