"""Add events table

Revision ID: f011b33ad061
Revises: 8f5df1273465
Create Date: 2025-12-04 16:20:55.175287+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f011b33ad061'
down_revision = '8f5df1273465'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_foreign_key(None, 'events', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('message_history', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('message_history', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('message_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('message_history', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_message_history_id'), 'message_history', ['id'], unique=False)
    op.create_foreign_key(None, 'message_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('notes', 'title',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('notes', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('notes', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index('ix_notes_category', table_name='notes')
    op.drop_index('ix_notes_is_pinned', table_name='notes')
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.create_foreign_key(None, 'notes', 'users', ['user_id'], ['id'])
    op.drop_column('notes', 'extra_data')
    op.drop_column('notes', 'reminder_datetime')
    op.drop_column('notes', 'priority')
    op.alter_column('users', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'tenant_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('notes', sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notes', sa.Column('reminder_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('notes', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.create_index('ix_notes_is_pinned', 'notes', ['is_pinned'], unique=False)
    op.create_index('ix_notes_category', 'notes', ['category'], unique=False)
    op.alter_column('notes', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('notes', 'tags',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('notes', 'title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_constraint(None, 'message_history', type_='foreignkey')
    op.drop_index(op.f('ix_message_history_id'), table_name='message_history')
    op.alter_column('message_history', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('message_history', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('message_history', 'tenant_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('message_history', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.alter_column('events', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('events', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.alter_column('conversations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('conversations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('conversations', 'tenant_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
