"""
Intent Detection Training Data - THEA-IA H03 FASE 2 (EXPANDED)
Spanish NLP training examples for 8 core intents

File: src/theaia/ml/intent_detector/training_data.py
Location: /src/theaia/ml/intent_detector/training_data.py
Generated: 20 Nov 2025 - 02:06 AM CET
Total examples: 320 (EXPANDED from 160)
Coverage: 8 intents, 40 examples each
"""

TRAINING_DATA = {
    # INTENT 1: CREAR EVENTO (AGENDA) - 40 ejemplos
    "create_event": [
        "Crear evento mañana a las 15:00",
        "Agendar reunión el próximo lunes",
        "Necesito un evento para el 25 de noviembre",
        "Programar cita con el doctor",
        "Crear una junta el viernes a las 10",
        "Agendar al cliente para mañana",
        "Programa una llamada a las 14:30",
        "Quiero crear un evento en mi calendario",
        "Programar el almuerzo del equipo",
        "Crear evento: presentación proyecto",
        "Agendar entrevista para próxima semana",
        "Necesito un evento recurrente cada lunes",
        "Crear reunión con María el miércoles",
        "Agendar conferencia en sala 3",
        "Programa una cita mañana por la tarde",
        "Crear evento de trabajo para el 30 de noviembre",
        "Agendar la junta con directivos",
        "Necesito programar una videollamada",
        "Crear evento personal para el gym",
        "Agendar descanso administrativo",
        "Nuevo evento para el cumpleaños",
        "Agregar cita médica al calendario",
        "Programar sesión de coaching",
        "Crear evento: training del equipo",
        "Agendar llamada internacional",
        "Necesito evento para la revisión anual",
        "Programar demo del producto",
        "Crear cita con recursos humanos",
        "Agendar visita al cliente",
        "Programar evento familiar",
        "Crear reunión urgente mañana",
        "Agendar presentación de resultados",
        "Programar sesión de feedback",
        "Crear evento: cena de trabajo",
        "Agendar revisión de código",
        "Programar kickoff del proyecto",
        "Crear evento semanal de planificación",
        "Agendar one-on-one con mi jefe",
        "Programar ceremonia de lanzamiento",
        "Crear evento: inauguración oficina",
    ],
    
    # INTENT 2: CREAR NOTA (NOTES) - 40 ejemplos
    "create_note": [
        "Crear nota importante",
        "Escribir nota: ideas del proyecto",
        "Nueva nota sobre las mejoras",
        "Anotar: hablar con Juan",
        "Crear nota recordatorio compras",
        "Escribir: puntos para la reunión",
        "Nueva nota: lista de tareas",
        "Apuntar: revisar código del módulo",
        "Crear nota de gastos",
        "Escribir notas del entrenamiento",
        "Nueva nota: feedback del cliente",
        "Anotar: llamar a proveedor",
        "Crear nota: bugs encontrados",
        "Escribir: estrategia de marketing",
        "Nueva nota: próximas vacaciones",
        "Apuntar: actualizar documentación",
        "Crear nota: ideas brillantes",
        "Escribir notas de la clase",
        "Nueva nota: contactos importantes",
        "Anotar: recordar cumpleaños",
        "Guardar nota rápida",
        "Crear apunte personal",
        "Escribir nota de investigación",
        "Nueva nota: mejoras del sistema",
        "Anotar: pendientes del día",
        "Crear nota: resumen de lecturas",
        "Escribir: objetivos del mes",
        "Nueva nota: lista de compras",
        "Apuntar: preguntas para la reunión",
        "Crear nota: reflexiones del día",
        "Escribir nota: plan de acción",
        "Nueva nota: ideas de contenido",
        "Anotar: decisiones importantes",
        "Crear nota de viaje",
        "Escribir: lecciones aprendidas",
        "Nueva nota: métricas del proyecto",
        "Apuntar: requisitos del cliente",
        "Crear nota: agenda personal",
        "Escribir nota: propuesta comercial",
        "Nueva nota: inventario de recursos",
    ],
    
    # INTENT 3: CREAR RECORDATORIO (REMINDERS) - 40 ejemplos
    "create_reminder": [
        "Recordarme mañana a las 9",
        "Crear recordatorio para el viernes",
        "Recordatorio: llamar a mamá",
        "Establecer alarma para las 15:00",
        "Recordarme en 2 horas",
        "Crear aviso para mañana",
        "Recordatorio diario a las 8",
        "Recordarme cada lunes",
        "Establecer alerta para el 15 de diciembre",
        "Recordatorio: pagar servicios",
        "Crear notificación para el próximo mes",
        "Recordarme antes de la junta",
        "Establecer recordatorio semanal",
        "Recordatorio: revisar emails",
        "Crear alarma cada miércoles",
        "Recordarme comprar leche",
        "Establecer aviso personalizado",
        "Recordatorio: enviar reporte",
        "Crear notificación urgente",
        "Recordarme cita dentista",
        "Alarma para tomar medicamento",
        "Recordatorio: renovar suscripción",
        "Crear aviso de cumpleaños",
        "Recordarme backup semanal",
        "Establecer recordatorio mensual",
        "Notificación para el deadline",
        "Recordarme regar plantas",
        "Crear alarma de descanso",
        "Recordatorio: fecha de entrega",
        "Establecer aviso de reunión",
        "Recordarme llamar al banco",
        "Crear notificación de pago",
        "Recordatorio: actualizar sistema",
        "Alarma para hacer ejercicio",
        "Recordarme revisar contratos",
        "Establecer recordatorio de seguimiento",
        "Notificación de vencimiento",
        "Recordarme enviar facturas",
        "Crear alarma de aniversario",
        "Recordatorio: cambiar contraseñas",
    ],
    
    # INTENT 4: CONSULTAR AGENDA (QUERY) - 40 ejemplos
    "query_agenda": [
        "Qué tengo mañana",
        "Cuál es mi agenda del próximo lunes",
        "Qué tengo programado el viernes",
        "Muestra mi calendario de esta semana",
        "Cuándo es mi próxima junta",
        "Qué eventos tengo hoy",
        "Consultar agenda de noviembre",
        "Cuál es mi próxima cita",
        "Qué tengo programado para mañana",
        "Mostrar eventos del mes",
        "Cuántos compromisos tengo",
        "Qué hay después de esta reunión",
        "Cuándo es el próximo evento",
        "Agenda de la próxima semana",
        "Qué tengo los próximos 7 días",
        "Eventos importantes del mes",
        "Cuál es mi horario de hoy",
        "Qué hay en mi calendario",
        "Próximas reuniones pendientes",
        "Cuándo estoy libre",
        "Ver calendario completo",
        "Mostrar eventos de diciembre",
        "Qué tengo el fin de semana",
        "Consultar horario semanal",
        "Cuándo tengo reuniones",
        "Mostrar agenda del día",
        "Qué eventos hay esta tarde",
        "Ver próximos compromisos",
        "Cuál es mi disponibilidad",
        "Mostrar calendario mensual",
        "Qué tengo programado hoy",
        "Ver eventos pendientes",
        "Cuándo son mis citas",
        "Mostrar agenda completa",
        "Qué hay en mi horario",
        "Ver próximas reuniones",
        "Cuándo tengo libre",
        "Mostrar eventos importantes",
        "Qué compromisos tengo",
        "Ver mi calendario personal",
    ],
    
    # INTENT 5: AYUDA (HELP) - 40 ejemplos
    "help": [
        "¿Qué puedes hacer?",
        "Ayuda",
        "Cuéntame tus funciones",
        "¿Cómo funciona esto?",
        "¿Qué comandos disponibles?",
        "Necesito ayuda",
        "¿Cómo usar la app?",
        "Explícame qué haces",
        "¿Cuáles son tus capacidades?",
        "Ayúdame a entender",
        "¿Cómo crear un evento?",
        "¿Cómo guardar notas?",
        "Instrucciones por favor",
        "¿Cuál es el comando para...?",
        "Guía de uso",
        "¿Cómo funciona el recordatorio?",
        "Manual de usuario",
        "¿Qué puedo hacer contigo?",
        "Opciones disponibles",
        "Muéstrame qué sabes hacer",
        "Necesito instrucciones",
        "¿Cómo empiezo?",
        "Enséñame a usar esto",
        "¿Qué comandos existen?",
        "Información de ayuda",
        "¿Cómo funciona el sistema?",
        "Guíame paso a paso",
        "¿Qué puedo preguntar?",
        "Tutorial básico",
        "¿Cómo consultar mi agenda?",
        "Ayuda con comandos",
        "¿Qué funciones tienes?",
        "Necesito soporte",
        "¿Cómo crear recordatorios?",
        "Explica las opciones",
        "¿Qué puedo hacer aquí?",
        "Ayuda para principiantes",
        "¿Cómo borrar eventos?",
        "Documentación disponible",
        "¿Qué tareas puedes hacer?",
    ],
    
    # INTENT 6: PROGRAMAR TAREAS (SCHEDULE) - 40 ejemplos
    "schedule_task": [
        "Programar tarea para mañana",
        "Agendar trabajo para el proyecto",
        "Establecer plazo para el 30 nov",
        "Programar deadline",
        "Agendar sprint planning",
        "Establecer fecha de entrega",
        "Programar revisión de código",
        "Agendar retrospectiva",
        "Establecer fecha de release",
        "Programar entrenamiento",
        "Agendar capacitación",
        "Establecer milestone",
        "Programar presentación",
        "Agendar sesión de trabajo",
        "Establecer checkpoint",
        "Programar standup diario",
        "Agendar one-on-one",
        "Establecer objetivo mensual",
        "Programar revisión trimestral",
        "Agendar planning session",
        "Programar tarea recurrente",
        "Agendar desarrollo feature",
        "Establecer fecha límite",
        "Programar testing phase",
        "Agendar deployment",
        "Establecer sprint review",
        "Programar grooming session",
        "Agendar daily meeting",
        "Establecer demo date",
        "Programar refactoring",
        "Agendar code review",
        "Establecer release candidate",
        "Programar maintenance window",
        "Agendar performance review",
        "Establecer quarterly goals",
        "Programar team building",
        "Agendar brainstorming",
        "Establecer launch date",
        "Programar user testing",
        "Agendar stakeholder meeting",
    ],
    
    # INTENT 7: FALLBACK (NO ENTIENDE) - 40 ejemplos
    "fallback": [
        "No entiendo",
        "Eso no tiene sentido",
        "¿Puedes repetir?",
        "No me queda claro",
        "¿Qué significa eso?",
        "No comprendo la pregunta",
        "Repite por favor",
        "No entendí",
        "¿Podrías reformular?",
        "No sé qué dices",
        "Eso es confuso",
        "No caché",
        "¿Cómo dijiste?",
        "Aclarame eso",
        "No me expliques así",
        "Usa palabras más simples",
        "No entiendo esa terminología",
        "¿Cuál es tu punto?",
        "Habla más claro",
        "No capto lo que dices",
        "Estoy confundido",
        "No comprendo nada",
        "¿De qué hablas?",
        "Eso no tiene lógica",
        "No puedo entender",
        "Demasiado complicado",
        "Simplifica la explicación",
        "No sigo tu razonamiento",
        "Perdí el hilo",
        "No me hace sentido",
        "¿Podrías ser más claro?",
        "No veo la relación",
        "Eso no cuadra",
        "Me perdí",
        "No logro comprender",
        "Muy confuso",
        "No entiendo el contexto",
        "¿A qué te refieres?",
        "No me quedó claro",
        "Necesito más claridad",
    ],
    
    # INTENT 8: BORRAR/ELIMINAR - 40 ejemplos
    "delete_item": [
        "Eliminar evento de mañana",
        "Borrar recordatorio",
        "Cancelar reunión",
        "Eliminar nota antigua",
        "Borrar evento duplicado",
        "Cancelar cita",
        "Eliminar recordatorio",
        "Borrar nota",
        "Cancelar evento",
        "Eliminar tarea",
        "Borrar evento del calendario",
        "Cancelar programación",
        "Eliminar recordatorio diario",
        "Borrar nota de trabajo",
        "Cancelar junta",
        "Eliminar evento personal",
        "Borrar recordatorio repetido",
        "Cancelar tarea",
        "Eliminar cita",
        "Borrar evento confirmado",
        "Quitar evento",
        "Remover recordatorio",
        "Cancelar alarma",
        "Eliminar nota vieja",
        "Borrar calendario",
        "Cancelar todos los eventos",
        "Eliminar agenda completa",
        "Borrar tareas pendientes",
        "Cancelar compromiso",
        "Eliminar notificación",
        "Borrar evento pasado",
        "Cancelar reunión semanal",
        "Eliminar recordatorio antiguo",
        "Borrar notas duplicadas",
        "Cancelar evento recurrente",
        "Eliminar tarea completada",
        "Borrar evento cancelado",
        "Cancelar cita médica",
        "Eliminar evento urgente",
        "Borrar recordatorio vencido",
    ],
}

# METADATA Y CONFIGURACIÓN
INTENT_METADATA = {
    "create_event": {"category": "calendar", "complexity": "medium", "examples_count": 40, "languages": ["es"], "entities": ["DATE", "TIME", "PERSON"]},
    "create_note": {"category": "notes", "complexity": "low", "examples_count": 40, "languages": ["es"], "entities": ["TOPIC", "TAG"]},
    "create_reminder": {"category": "reminders", "complexity": "medium", "examples_count": 40, "languages": ["es"], "entities": ["DATE", "TIME", "FREQUENCY"]},
    "query_agenda": {"category": "calendar", "complexity": "low", "examples_count": 40, "languages": ["es"], "entities": ["DATE", "RANGE"]},
    "help": {"category": "system", "complexity": "low", "examples_count": 40, "languages": ["es"], "entities": []},
    "schedule_task": {"category": "tasks", "complexity": "medium", "examples_count": 40, "languages": ["es"], "entities": ["DATE", "PROJECT", "TASK"]},
    "fallback": {"category": "system", "complexity": "low", "examples_count": 40, "languages": ["es"], "entities": []},
    "delete_item": {"category": "calendar", "complexity": "low", "examples_count": 40, "languages": ["es"], "entities": ["ITEM_TYPE", "DATE"]},
}

def get_training_examples(intent: str = None) -> dict:
    if intent:
        return {intent: TRAINING_DATA.get(intent, [])}
    return TRAINING_DATA

def get_total_examples() -> int:
    return sum(len(examples) for examples in TRAINING_DATA.values())

def get_intents_list() -> list:
    return list(TRAINING_DATA.keys())

STATS = {
    "total_examples": get_total_examples(),
    "total_intents": len(TRAINING_DATA),
    "intents": get_intents_list(),
    "version": "2.0",
    "language": "Spanish (es)",
    "created": "20 Nov 2025",
    "expanded": True,
}

if __name__ == "__main__":
    print(f"Training Data Loaded: {STATS['total_examples']} examples")
    print(f"Intents: {STATS['total_intents']}")
    print(f"Intent List: {STATS['intents']}")
