name: THEA IA • CI/CD Enterprise Workflow

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libpq-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio pytest-cov black flake8 isort mypy

      - name: Lint - Code Quality
        run: |
          black --check src/
          isort --check-only src/
          flake8 src/ --max-line-length=100
          mypy src/ --install-types --non-interactive

  tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-asyncio pytest-cov

      - name: Run Tests
        run: pytest -v --cov=src/theaia --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: ./coverage.xml
          verbose: true

  docker:
    runs-on: ubuntu-latest
    needs: [setup, tests]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t thea-ia:latest -f Dockerfile.optimized .

      - name: Verify build success
        run: docker image inspect thea-ia:latest > /dev/null

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    environment:
      name: production
    steps:
      - name: Pull repository
        uses: actions/checkout@v4

      - name: Deploy to Railway
        if: github.ref == 'refs/heads/main'
        uses: railwayapp/cli-action@v3
        with:
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}
          service: "thea-ia"
          path: "."
